### ISSUE TITLE
run-test, error, with Python 3.7.4

### ISSUE THREAD

**Issue by michaelsjackson** [tmbarchive/ocropy#337]
```
./run-test
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-nlbin", line 10, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 166, in <module>
    from . import random
  File "/usr/local/lib/python2.7/dist-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
ImportError: /usr/local/lib/python2.7/dist-packages/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf

```

**Comment by amitdo** [comment]
See #334.
